### PR TITLE
Cassandra 12250 check for indexes

### PR DESCRIPTION
**Pull request by mambocab**
This runs locally, so I think the code is good. In progress on CassCI here:

http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/180/console

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Lgtm if the CI results pass

**Comment by knifewine** [comment]
Looks like the test run went well, +1 (though Travis is upset for some reason)

**Comment by mambocab** [comment]
I believe that's my fault from ninja-ing in a `known_failure` incorrectly earlier.

**Comment by ptnapoleon** [comment]
Yeah, it's fixed on master now, so merging this will be fine

**Pull request merged**
