### PR TITLE
Never use the thrift port.

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab to review

### CODE REVIEW

**Comment by mambocab** [comment]
Are we confident that it won't be None as long as the node is running? If not, we should add a check for that.

**Comment by ptnapoleon** [comment]
What do we want to do if it is None?

**Comment by ptnapoleon** [comment]
Also, looking at the ccm code, I am very sure it will never be None. Someone would need to create a Node object, and explicitly pass in None for the binary interface, which should screw up launching the actual C* process.

**Comment by mambocab** [comment]
If you're sufficiently confident about that, then use this as-is. If we wanted fail fast, I'd raise a `RuntimeError` with a message about the problem.

**Comment by ptnapoleon** [comment]
It should just fail out with a KeyError, but I will improve the message, then ping you here.

**Comment by ptnapoleon** [comment]
Thoughts?

**Comment by mambocab** [comment]
Catch a `KeyError` instead of a base `Exception` and I'm +1 -- we don't want to erroneously catch a random operating system error or something.

**Comment by ptnapoleon** [comment]
It isn't always a KeyError though. I can also make it get a TypeError, and I'm not sure that those two constitute an exhaustive list of potential problems. But I'm pretty (read 90%) sure that since I'm using `except Exception:` and not `except:` I will only catch things propagated by Python, and OS level signals will still work, i.e., I'm not breaking sigkill. Thoughts? I could just catch Key and Type, and call it a day.

**Comment by mambocab** [comment]
Oh, OS stuff doesn't inherit from Exception, TIL. That is good. I'm +1.

**Comment by ptnapoleon** [comment]
Yup. Tyler taught me that.

**Pull request merged**
