### PR TITLE
DESCRIBE TABLE -> CREATE TABLE round trip

### PR DESCRIPTION
**Pull request by mambocab**
This tests for the bug described in CASSANDRA-9064. It will probably be superseded at some point by CVH, but for the moment it'll be helpful.

Review this in separate commits -- the 2 most recent commits are whitespace fixes and import sorting. I've run the tests locally and they still pass, so I don't think I screwed anything up in fixing whitespace.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1, except I'm going to politely ask that before merge, you rebase and fix the typo in the first commit message, please. It's `9064` not `9604`. That's going to confuse people going through history.

**Comment by mambocab** [comment]
You may demand such a thing impolitely -- readable history is important.

**Comment by mambocab** [comment]
Fixed the commit message and rebased onto master. We should be good for Travis, but I'm going to wait just in case.

**Comment by mambocab** [comment]
Travis is happy :tada: Merging.

**Pull request merged**
