### PR TITLE
Fix tracing tests after improving the logging message

### PR DESCRIPTION
**Pull request by ifesdjeen**
For https://issues.apache.org/jira/browse/CASSANDRA-11706

### CODE REVIEW

**Comment by ptnapoleon** [comment]
It's hard to tell why these changes are needed, but the code looks fine, +1

**Comment by ifesdjeen** [comment]
@ptnapoleon previously message was like that:
```
ERROR [ScheduledTasks:1] 2016-08-25 18:26:03,411 Tracing.java:107 - Cannot use class org.apache.cassandra.tracing.TracingImpl for tracing (Default constructor for Tracing class 'org.apache.cassandra.tracing.TracingImpl' is inaccessible.), ignoring by defaulting on normal tracing
```

after the change the full stack trace is available:

```
ERROR [ScheduledTasks:1] 2016-08-25 17:53:03,352 Tracing.java:107 - Cannot use class org.apache.cassandra.tracing.TracingImpl for tracing, ignoring by defaulting to normal tracing
org.apache.cassandra.exceptions.ConfigurationException: Default constructor for Tracing class 'org.apache.cassandra.tracing.TracingImpl' is inaccessible.
        at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:529) ~[main/:na]
        at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:518) ~[main/:na]
        at org.apache.cassandra.tracing.Tracing.<clinit>(Tracing.java:101) ~[main/:na]
        at org.apache.cassandra.net.MessageOut.<init>(MessageOut.java:59) [main/:na]
        at org.apache.cassandra.hints.HintResponse.<clinit>(HintResponse.java:35) [main/:na]
        at org.apache.cassandra.net.MessagingService$3.<init>(MessagingService.java:346) [main/:na]
        at org.apache.cassandra.net.MessagingService.<clinit>(MessagingService.java:343) [main/:na]
        at org.apache.cassandra.service.StorageService.<init>(StorageService.java:246) [main/:na]
        at org.apache.cassandra.service.StorageService.<clinit>(StorageService.java:141) [main/:na]
        at org.apache.cassandra.locator.DynamicEndpointSnitch.updateScores(DynamicEndpointSnitch.java:307) [main/:na]
        at org.apache.cassandra.locator.DynamicEndpointSnitch.access$000(DynamicEndpointSnitch.java:48) [main/:na]
        at org.apache.cassandra.locator.DynamicEndpointSnitch$1.run(DynamicEndpointSnitch.java:92) [main/:na]
        at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118) [main/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

arguably more visible / clearer exception.

**Comment by ptnapoleon** [comment]
Looks great, Thanks Alex, +1

**Comment by michaelsembwever** [comment]
:+1:

**Comment by michaelsembwever** [comment]
C* ticket has been committed.

**Comment by ifesdjeen** [comment]
Merging to avoid test failures.

**Pull request merged**
