### PR TITLE
get more debug info in tracing_unknown_impl_test

### PR DESCRIPTION
**Pull request by mambocab**
Just adds some debug printing for https://issues.apache.org/jira/browse/CASSANDRA-11465.

### CODE REVIEW

**Comment by mambocab** [comment]
Trying it here: http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/55/

**Comment by mambocab** [comment]
I believe I have fixed the problems that made the tests explode -- the log watcher picked up errors in `prepare` calls because `ignore_log_errors` wasn't set.

@knifewine This might be a good debugging case for the log watcher -- looks like the dtests generally don't do teardown right on `SIGINT`?

**Comment by ptnapoleon** [comment]
+1 on the debug changes. Shouldn't we SIGTERM, not SIGINT?

**Comment by mambocab** [comment]
No, I do mean `SIGINT`. `unittest` has an option to finish the current test on `^C`:

https://docs.python.org/2/library/unittest.html#cmdoption-unittest-c

Doesn't look like we can use it directly through `nose` but we might look into it.

**Comment by knifewine** [comment]
+1 on the changes

not certain I understand how the log watcher is misbehaving, but wonder if it could be forcing main thread termination before it's been able to complete all of the teardown.

**Comment by mambocab** [comment]
Yeah, I think that's what's happening. I don't know if the failure results reflect this, but maybe the log-watching function is being called during teardown, since the thread doesn't stop running until the main thread exits?

**Comment by mambocab** [comment]
But, thank you for the review. Merging.

**Pull request merged**
