### PR TITLE
change assert to self.assertIn

### PR DESCRIPTION
**Pull request by c-kodman**

### CODE REVIEW

**Comment by mambocab** [comment]
`in` and `re.search` aren't the same. Have a look in the `unittest.TestCase` documentation; there should be a useful regex assertion in there somewhere.

**Comment by ptnapoleon** [comment]
They are if you use re.search to find a string literal

**Comment by ptnapoleon** [comment]
We might need to change the escape chars, but there's no reason to use re.search if we aren't using a regex

**Comment by mambocab** [comment]
Oh, yup. My mistake. `assertIn` is fine then, but some escape characters will have to be removed I believe.

**Comment by ptnapoleon** [comment]
+1

**Pull request merged**
