### PR TITLE
Test for CASSANDRA-9590

### PR DESCRIPTION
**Pull request by spodkowinski**
Do not merge before ticket has been commited.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Can you fix the style complaints travis has?

**Comment by spodkowinski** [comment]
Style check issues fixed, build passed.

**Comment by ptnapoleon** [comment]
Did you see Robert's comment on a fix to make, at https://issues.apache.org/jira/browse/CASSANDRA-9590?focusedCommentId=14730528&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14730528 ?

**Comment by spodkowinski** [comment]
I've changed the ssl_opts to use the individual cert instead of the keystore, as suggested by Robert. Both variants work for me (Linux oracle jdk1.8.0_51).

**Comment by ptnapoleon** [comment]
Then +1

**Pull request merged**
