### PR TITLE
Cassandra 11394

### PR DESCRIPTION
**Pull request by mambocab**
This won't break the existing test, but there's a companion PR over at https://github.com/pcmanus/ccm/pull/484. This is kind of a debugging step for some flaps we've seen.

### CODE REVIEW

**Comment by mambocab** [comment]
Pushed with a new, more detailed, commit message.

**Comment by ptnapoleon** [comment]
@mambocab and @knifewine is this something we should have merged, still merge, review, etc?

**Comment by mambocab** [comment]
I don't know if this is useful any longer, this test hasn't flaked in 3 months. Thoughts?

**Comment by ptnapoleon** [comment]
I'm okay closing then

**Comment by mambocab** [comment]
Fab, thank you.

**Pull request closed without merging**
