### PR TITLE
Add test for CASSANDRA-8366

### PR DESCRIPTION
**Pull request by aboudreault**
Add test for CASSANDRA-8366

### CODE REVIEW

**Comment by aboudreault** [comment]
@mshuler Since this test is long, can we change the default jenkins run command for: nosetests -a '!long' To not run long tests daily.

**Comment by ptnapoleon** [comment]
Does this supercede #130?

**Comment by aboudreault** [comment]
No, I will go back on 130 soon.... not sure if it is still worth adding it.

**Comment by ptnapoleon** [comment]
I am +1 on the test. Your calculation for load size does duplicate the work that @mambocab did in #182, which he will be extracting and putting into ccm so you can just call node.data_size(). What you have is fine for now, as long as we make sure to change it once the CCM fix is in.

**Comment by aboudreault** [comment]
+1, nice addition Jim. Merging this one. I have added an entry in my backlog to recheck 182 status and do the proper change in my code.

**Comment by mshuler** [comment]
I couple test runs and the annotation looks fine to me - I'll add -a '!long' to the normal commit jobs. The time difference on just incremental_repair_test.py was 40 min vs 9 min w/o multiple_subsequent_repair_test

**Comment by aboudreault** [comment]
Thanks @mshuler! It seems longer than locally though.. it was more 20-25 minutes during my development. Probably due to the machine load.

**Pull request merged**
