### PR TITLE
add 3.1 to upgrade_through_versions

### PR DESCRIPTION
**Pull request by knifewine**

### CODE REVIEW

**Comment by knifewine** [comment]
paging @ptnapoleon

**Comment by knifewine** [comment]
damnit, need to remove that last line, one sec.

**Comment by knifewine** [comment]
Looks like there's an assumption being made in the code that's causing it to break on 3.1, so not yet ready for merge.

**Comment by ptnapoleon** [comment]
I'll hold off on checking it then

**Comment by knifewine** [comment]
@ptnapoleon now that we have a 3.1 tag this should work fine.

**Comment by ptnapoleon** [comment]
+1

**Comment by ptnapoleon** [comment]
Don't we also want a path that goes from 3.0 to trunk, skipping 3.1?

**Comment by knifewine** [comment]
Don't we also want a path that goes from 3.0 to trunk, skipping 3.1?

quite possibly, but I think that will need to wait until we better figure things out

**Pull request merged**
