### PR TITLE
driver version doc

### PR DESCRIPTION
**Pull request by mambocab**
I don't know a good way to phrase this without a long explanation of what's going on here. Requesting feedback/edits from @ptnapoleon and feedback from @spodkowinski if you're so inclined.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1

**Comment by spodkowinski** [comment]
+1, thanks for the update

**Comment by mambocab** [comment]
Thanks for the earlier PR and your input, @spodkowinski. Merging.

**Comment by mambocab** [comment]
For the record, this subsumed #595.

**Pull request merged**
