### PR TITLE
Ignore 2.1 errors on non-upgraded node

### PR DESCRIPTION
**Pull request by ptnapoleon**
in mixed version cluster.

@josh-mckenzie to review

### CODE REVIEW

**Comment by ptnapoleon** [comment]
@mambocab as well, as I just made some changes based on his input

**Comment by mambocab** [comment]
What were the errors? I think this could use a comment, explaining why we need to do this, how it accomplishes that, and an example of the error or errors we want to ignore.

**Comment by ptnapoleon** [comment]
Comment pushed. Also added the version check earlier, in preparation for your refactor.

**Comment by josh-mckenzie** [comment]
Looks good.

**Comment by mambocab** [comment]
+1, thanks!

**Pull request merged**
