### PR TITLE
New test for CASSANDRA-13185

### PR DESCRIPTION
**Pull request by stef1927**
This is a new test for [CASSANDRA-13185](https://issues.apache.org/jira/browse/CASSANDRA-13185).

### CODE REVIEW

**Comment by ptnapoleon** [comment]
So, this looks good, but I'm a bit paranoid about the fact that our final assertion is comparing the output of two `SELECT *` calls. If either the python driver, or the select statement have a bug in handling these dates, we won't catch it (and it might mask a COPY issue). I'd feel safer if we compared `args` to `result` or `new_result` at some point.

**Comment by thobbs** [comment]
Agreed, it would be good to have a least a couple of basic sanity checks on the returned dates.  I don't think we have to check every value exactly, just a couple of outliers.

**Comment by stef1927** [comment]
Thanks for the review. I've added a check in https://github.com/riptano/cassandra-dtest/pull/1445/commits/019d31f2b2152e35f448b2b1f13a142614d71782. I plan to squash it before merging.

**Comment by ptnapoleon** [comment]
+1

**Comment by stef1927** [comment]
Thanks, squashed, merging now.

**Pull request merged**
