### PR TITLE
Fix enabling of jmx auth on windows

### PR DESCRIPTION
**Pull request by beobal**

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1

**Comment by mambocab** [comment]
Ping @beobal, is this ready for merge?

**Comment by beobal** [comment]
@mambocab sorry, should've closed this earlier. I couldn't test the windows-specific behaviour, Joel picked it up & is currently awaiting feedback before opening a new PR to replace it. See CASSANDRA-11730 for details.

**Comment by mambocab** [comment]
No worries, thanks for updating!

**Pull request closed without merging**
