### PR TITLE
added counters upgrade test with rf=2 and CL=ALL

### PR DESCRIPTION
**Pull request by pauloricardomg**
Tests for CASSANDRA-10470

### CODE REVIEW

**Comment by mambocab** [comment]
Will this be necessary if I add cl=ALL to the 3-node, rf=3 tests here: https://github.com/riptano/cassandra-dtest/pull/616 ?

**Comment by mambocab** [comment]
Pinging @pauloricardomg: is this necessary given the changes in #616?

**Comment by pauloricardomg** [comment]
Sorry, missed the first update. No, this should not be necessary anymore after #616. Closing it then.

**Comment by mambocab** [comment]
No need to apologize, that's what pinging is for. Thanks!

**Pull request closed without merging**
