### PR TITLE
CASSANDRA-11866 test repair works with -st -et and a column family sp…

### PR DESCRIPTION
**Pull request by brianwawok**
…ecified

### CODE REVIEW

**Comment by ptnapoleon** [comment]
@knifewine can you review, please

**Comment by knifewine** [comment]
checked that test fails prior to 11866 cassandra fix on 2.1, and passes after.

I don't have great depth with repair and its various options, but code looks fine to me.

+1

**Comment by pauloricardomg** [comment]
had a quick look at the patch and the repair side looks good too, so +1 from me as well :)

**Comment by ptnapoleon** [comment]
C* ticket is merged, so merging this

**Pull request merged**
