### PR TITLE
Move sstableloader upgrade tests to upgrade_tests/storage_engine_upgrade_test

### PR DESCRIPTION
**Pull request by pauloricardomg**
Also fixed create_schema to create compact tables when that is set.

~~Submitted CI run: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/7/~~

EDIT: previous CI run failed, resubmitted here: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy2-dtest/1/

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1 if CI works out

**Comment by ptnapoleon** [comment]
This appears to have not worked on CI, and also needs rebased

**Comment by pauloricardomg** [comment]
Rebased and resubmitted: http://cassci.datastax.com/job/pauloricardomg-trunkcopy2-dtest/2/

**Comment by ptnapoleon** [comment]
@mshuler Are you able to tell what's going wrong with this CI job ^ ?

**Comment by mshuler** [comment]
```
00:07:16 test_network_topology_strategy (consistency_test.TestAvailability) ... Build timed out (after 20 minutes). Marking the build as aborted.
00:27:16 Build was aborted
```

If you look at the console logs where it's tar'ing up the logs, every build server has ccm node logs, similar to:
```
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node1/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node1/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node1/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node1/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node2/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node2/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node3/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node3/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node3/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node3/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node4/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node4/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node4/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node4/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node5/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node5/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node6/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node6/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node6/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node6/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node7/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node7/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node7/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node7/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node8/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node8/logs/gc.log.0.current
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node8/logs/debug.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node8/logs/system.log
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node9/logs/
00:27:23 /mnt/tmp/dtest-P5cPt7/test/node9/logs/gc.log.0.current
```

Those are hung dtests and those logs could be helpful. The fact that some test is starting 9 ccm nodes could also be a clue - all the servers have 9 ccm node logs, it appears. Whatever that is should be moved to long_dtest and run on larger instances.

**Comment by mshuler** [comment]
```
00:05:37 test_network_topology_strategy (consistency_test.TestAvailability) ... ok
00:06:18 test_network_topology_strategy (consistency_test.TestAvailability) ... ok
00:07:16 test_network_topology_strategy (consistency_test.TestAvailability) ... Build timed out (after 20 minutes). Marking the build as aborted.
```

That's interesting :)

**Comment by mshuler** [comment]
The test buckets are all empty, except for the first, which lists all the *.py files. Without the list, they all ran everything.

http://cassci.datastax.com/job/pauloricardomg-trunkcopy2-dtest/2/artifact/cassandra-dtest/

**Comment by pauloricardomg** [comment]
thank you @mshuler @ptnapoleon I will have a better look to find out the root cause

**Comment by mshuler** [comment]
This is the root cause:
```
21:16:40 + /var/lib/jenkins/datastax-jenkins-util/job_bucketizer.py -u http://cassci.datastax.com -j pauloricardomg-trunkcopy2-dtest -n 17 -c conf/trunk_test-select.cfg -v
21:16:41 nose stdout:
21:16:41 ====================
21:16:41 nose.config: INFO: Set working dir to /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest
21:16:41 nose.config: INFO: Working directory /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest is a package; adding to sys.path
21:16:41 nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
21:16:41 nose.plugins.nose_test_select: INFO: {'exclude': ['/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAvailability.test_network_topology_strategy', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAvailability.test_network_topology_strategy_each_quorum', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/tools.py:TestAvailability.test_network_topology_strategy_each_quorum', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAccuracy.test_network_topology_strategy_users', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAccuracy.test_network_topology_strategy_each_quorum_users', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/tools.py:TestAccuracy.test_network_topology_strategy_each_quorum_users', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAccuracy.test_network_topology_strategy_each_quorum_counters', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/tools.py:TestAccuracy.test_network_topology_strategy_each_quorum_counters', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/consistency_test.py:TestAccuracy.test_network_topology_strategy_counters', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/replication_test.py:ReplicationTest.network_topology_test', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/replication_test.py:SnitchConfigurationUpdateTest.test_rf_collapse_gossiping_property_file_snitch_multi_dc', '/var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/replication_test.py:SnitchConfigurationUpdateTest.test_rf_expand_gossiping_property_file_snitch_multi_dc'], 'include': []}
21:16:41 nose.selector: INFO: /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/findlibjemalloc.sh is executable; skipped
21:16:41 nose.selector: INFO: /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/linter_check.sh is executable; skipped
21:16:41 nose.selector: INFO: /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/run_dtests.py is executable; skipped
21:16:41 nose.selector: INFO: /var/lib/jenkins/jobs/pauloricardomg-trunkcopy2-dtest/workspace/cassandra-dtest/thrift_bindings/v22/Cassandra-remote is executable; skipped
21:16:41 #1 auth_test.py:None ... ok
21:16:41 #2 batch_test.py:None ... ok
21:16:41 #3 bootstrap_test.py:None ... ok
21:16:41 #4 cdc_test.py:None ... ok
21:16:41 #5 cfid_test.py:None ... ok
21:16:41 #6 commitlog_test.py:None ... ok
21:16:41 #7 compaction_test.py:None ... ok
21:16:41 #8 compression_test.py:None ... ok
21:16:41 #9 concurrent_schema_changes_test.py:None ... ok
21:16:41 #10 configuration_test.py:None ... ok
21:16:41 #11 consistency_test.py:None ... ok
21:16:41 #12 consistent_bootstrap_test.py:None ... ok
21:16:41 #13 counter_tests.py:None ... ok
21:16:41 #14 cql_prepared_test.py:None ... ok
21:16:41 #15 cql_tests.py:None ... ok
21:16:41 #16 cql_tracing_test.py:None ... ok
21:16:41 #17 cqlsh_tests/cqlsh_copy_tests.py:None ... ok
21:16:41 #18 cqlsh_tests/cqlsh_tests.py:None ... ok
21:16:41 #19 delete_insert_test.py:None ... ok
21:16:41 #20 deletion_test.py:None ... ok
21:16:41 #21 disk_balance_test.py:None ... ok
21:16:41 #22 global_row_key_cache_test.py:None ... ok
21:16:41 #23 hintedhandoff_test.py:None ... ok
21:16:41 #24 internode_ssl_test.py:None ... ok
21:16:41 #25 jmx_auth_test.py:None ... ok
21:16:41 #26 jmx_test.py:None ... ok
21:16:41 #27 jmxmetrics_test.py:None ... ok
21:16:41 #28 json_test.py:None ... ok
21:16:41 #29 json_tools_test.py:None ... ok
21:16:41 #30 largecolumn_test.py:None ... ok
21:16:41 #31 materialized_views_test.py:None ... ok
21:16:41 #32 Calling a rate-limited function's func attribute calls the wrapped function. ... ok
21:16:41 #33 Calling a rate-limited function's func attribute is not affected by rate limiting. ... ok
21:16:41 #34 Calling a rate-limited function delegates to the wrapped function. ... ok
21:16:41 #35 If you call a rate-limited function a second time after the time limit is up, it is called twice. ... ok
21:16:41 #36 A rate-limited function works as expected. ... ok
21:16:41 #37 Rate-limited functions can be initialized with limit and func keyword arguments. ... ok
21:16:41 #38 Rate-limited functions can be initialized with the function and limit in that order. ... ok
21:16:41 #39 If you call a rate-limited function during the time limit, last_called is not set to a new value. ... ok
21:16:41 #40 If you call a rate-limited function, last_called is set to a new value. ... ok
21:16:41 #41 If you call a rate-limited function before the time limit is up, it is called not called. ... ok
21:16:41 #42 A rate-limited function's repr is what we expect. ... ok
21:16:41 #43 metadata_tests.py:None ... ok
21:16:41 #44 mixed_version_test.py:None ... ok
21:16:41 #45 multidc_putget_test.py:None ... ok
21:16:41 #46 native_transport_ssl_test.py:None ... ok
21:16:41 #47 nodetool_test.py:None ... ok
21:16:41 #48 offline_tools_test.py:None ... ok
21:16:41 #49 paging_test.py:None ... ok
21:16:41 #50 paxos_tests.py:None ... ok
21:16:41 #51 pending_range_test.py:None ... ok
21:16:41 #52 prepared_statements_test.py:None ... ok
21:16:41 #53 pushed_notifications_test.py:None ... ok
21:16:41 #54 putget_test.py:None ... ok
21:16:41 #55 range_ghost_test.py:None ... ok
21:16:41 #56 read_repair_test.py:None ... ok
21:16:41 #57 rebuild_test.py:None ... ok
21:16:41 #58 repair_tests/deprecated_repair_test.py:None ... ok
21:16:41 #59 repair_tests/incremental_repair_test.py:None ... ok
21:16:41 #60 repair_tests/repair_test.py:None ... ok
21:16:41 #61 replace_address_test.py:None ... ok
21:16:41 #62 replication_test.py:None ... ok
21:16:41 #63 schema_metadata_test.py:None ... ok
21:16:41 #64 schema_test.py:None ... ok
21:16:41 #65 scrub_test.py:None ... ok
21:16:41 #66 secondary_indexes_test.py:None ... ok
21:16:41 #67 snapshot_test.py:None ... ok
21:16:41 #68 snitch_test.py:None ... ok
21:16:41 #69 sslnodetonode_test.py:None ... ok
21:16:41 #70 sstable_generation_loading_test.py:None ... ok
21:16:41 #71 sstablesplit_test.py:None ... ok
21:16:41 #72 sstableutil_test.py:None ... ok
21:16:41 #73 stress_tool_test.py:None ... ok
21:16:41 #74 super_column_cache_test.py:None ... ok
21:16:41 #75 super_counter_test.py:None ... ok
21:16:41 #76 thrift_hsha_test.py:None ... ok
21:16:41 #77 thrift_tests.py:None ... ok
21:16:41 #78 topology_test.py:None ... ok
21:16:41 #79 ttl_test.py:None ... ok
21:16:41 #80 udtencoding_test.py:None ... ok
21:16:41 #81 upgrade_crc_check_chance_test.py:None ... ok
21:16:41 #82 upgrade_internal_auth_test.py:None ... ok
21:16:41 #83 upgrade_supercolumns_test.py:None ... ok
21:16:41 #84 upgrade_tests/cql_tests.py:None ... ok
21:16:41 #85 upgrade_tests/paging_test.py:None ... ok
21:16:41 #86 upgrade_tests/regression_test.py:None ... ok
21:16:41 #87 upgrade_tests/storage_engine_upgrade_test.py:None ... ok
21:16:41 #88 upgrade_tests/upgrade_through_versions_test.py:None ... ok
21:16:41 #89 user_functions_test.py:None ... ok
21:16:41 #90 user_types_test.py:None ... ok
21:16:41 #91 wide_rows_test.py:None ... ok
21:16:41 #92 write_failures_test.py:None ... ok
21:16:41 
21:16:41 ----------------------------------------------------------------------
21:16:41 Ran 92 tests in 0.522s
21:16:41 
21:16:41 OK
21:16:41 
21:16:41 nose stderr:
21:16:41 ====================
21:16:41 None
21:16:41 Jenkins has no build history for pauloricardomg-trunkcopy2-dtest, using default buckets
21:16:41 test_bucket.000 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.001 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.002 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.003 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.004 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.005 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.006 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.007 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.008 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.009 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.010 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.011 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.012 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.013 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.014 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.015 -    0 tests - expected duration: 0:00:00
21:16:41 test_bucket.016 -    0 tests - expected duration: 0:00:00
21:16:41 There were broken test file(s)! 81 test file(s) were broken. Test file name(s) added to 'test_bucket.000'.
```

**Comment by ptnapoleon** [comment]
We shouldn't be running those big tests, they should be excluded since they're in long_dtest.

**Comment by ptnapoleon** [comment]
Is Paulo's change to `__init__.py` the problem? Nothing else could possibly cause all those bucketizer problems

**Comment by pauloricardomg** [comment]
I'm trying a new run without the `__init__.py`, let's see how this goes: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/12/

This is indeed very strange..

**Comment by pauloricardomg** [comment]
new run without `__init__.py`: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/13/ :pray:

**Comment by ptnapoleon** [comment]
Well it is good to learn that adding an __init__.py to dtest totally hoses it

**Comment by ptnapoleon** [comment]
You're still committing the removal of the __init__ in repair_tests/ which shouldn't happen

**Comment by ptnapoleon** [comment]
After that is fixed, +1

**Comment by pauloricardomg** [comment]
> You're still committing the removal of the init in repair_tests/ which shouldn't happen

oops, fixed this and resubmitted test:
http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/14/

**Comment by ptnapoleon** [comment]
Needs a rebase, but +1! Thanks Paulo, sorry about those linter errors that got into master

**Comment by pauloricardomg** [comment]
rebased and resubmitted:
http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/15/

**Comment by ptnapoleon** [comment]
@knifewine Can you help here? I believe Paulo's intent is to make these tests no longer run as part of the dtests, but only as part of the upgrade tests, but that is not happening

**Comment by pauloricardomg** [comment]
There was a failure with `upgrade_tests.storage_engine_upgrade_test.TestLoadKaSStables.sstableloader_uppercase_keyspace_name_test` because this is not supposed to be on `BaseSStableLoaderTest` but on `TestSSTableGenerationAndLoading` instead, so I updated the patch to reflect that and also added a warning that new sstableloader tests should be added to `TestSSTableGenerationAndLoading`.

Resubmitted ci run: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/16/

**Comment by pauloricardomg** [comment]
New dtest run looks good. I also added the following annotation to the tests in `storage_engine_upgrade_test.py`: `@skipIf(not UPGRADE_TEST_RUN, 'set UPGRADE_TEST_RUN=true to run upgrade tests')` - This annotation is used by `UpgradeTester` to run upgrade tests only during the upgrade test run, so it should hopefully be good now!

**Comment by ptnapoleon** [comment]
+1, thanks Paulo! Merge away

**Comment by pauloricardomg** [comment]
Thanks all for the review!

**Pull request merged**
