### PR TITLE
Retry more in repair test

### PR DESCRIPTION
**Pull request by mambocab**
2 simple changes to hopefully address [CASSANDRA-12162](https://issues.apache.org/jira/browse/CASSANDRA-12162).

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1

**Comment by mambocab** [comment]
Just occurred to me: are we confident enough that this will address the ticket to close it?

**Comment by ptnapoleon** [comment]
Not until you multiplex it?

**Comment by mambocab** [comment]
Yep. I'll merge, multiplex, and follow up.

**Pull request merged**
