### PR TITLE
Use long message to provide more information about failed query.

### PR DESCRIPTION
**Pull request by ifesdjeen**
The patch is related to [CASSANDRA-12025](https://issues.apache.org/jira/browse/CASSANDRA-12025).

### CODE REVIEW

**Comment by mambocab** [comment]
Could you show us the difference between these failures with and without the `self.longMessage = True`? This is the first I've seen it, and [it seems to be `True` by default](https://github.com/python/cpython/blob/2410a06c294d9b091f39f09f638c1d83d0ff440e/Lib/unittest/case.py#L371). From what I read in the `unittest` docs, it looks like `longMessage` just makes failred assertions print the `msg` parameter, which they do by default.

**Comment by ptnapoleon** [comment]
Bump, why set longMessage to True?

**Comment by ifesdjeen** [comment]
The output without `longMessage: True` is: 

```
AssertionError: Query failed with page size 2
```

With:

```
AssertionError: Lists differ: [[4, 7, 8, 9], [4, 8, 9, 10], ... != [[4, 7, 8, 91], [4, 8, 9, 10],...

First differing element 0:
[4, 7, 8, 9]
[4, 7, 8, 91]

- [[4, 7, 8, 9], [4, 8, 9, 10], [4, 9, 10, 11]]
+ [[4, 7, 8, 91], [4, 8, 9, 10], [4, 9, 10, 11]]
?             +
 : Query failed with page size 2
```

I'm not sure why it's not set to True for me by default though...

**Comment by mambocab** [comment]
Whoa, I have no idea where that gets set to `False`, but it sure does:

```python
~/scratch  
(dtest) ❯ cat test_longMessage.py 
import unittest


class TestLongMessage(unittest.TestCase):
    def test_longMessage(self):
        assert self.longMessage
                                                                                                                                                                                                                                        
~/scratch  
(dtest) ❯ nosetests test_longMessage.py 
F
======================================================================
FAIL: test_longMessage (test_longMessage.TestLongMessage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mambocab/tmp/scratch-1467209909/test_longMessage.py", line 6, in test_longMessage
    assert self.longMessage
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

But that looks good. You can feel free to set it to `True` for this test, as that message is more useful. You don't have to set it back to `False`; there's a new `Tester` object created for every test, so it won't affect the next test run.

**Comment by ifesdjeen** [comment]
Great, thank you!

**Comment by mambocab** [comment]
@ptnapoleon, any objections? LGTM.

**Comment by mambocab** [comment]
Eh, I'm sure Philip won't mind it, the change is fine. Merging.

**Comment by mambocab** [comment]
Thanks @ifesdjeen

**Pull request merged**
