### PR TITLE
Fix for CASSANDRA-10459

### PR DESCRIPTION
**Pull request by pauloricardomg**
[CASSANDRA-8670](https://issues.apache.org/jira/browse/CASSANDRA-8670) was added on 2.2, but for some reason it has a @since(3.0) annotation,

### CODE REVIEW

**Comment by pauloricardomg** [comment]
surprinsingly enough, the test passes on 2.2, but not on 3.0 :p I'm checking what's going on.

**Comment by mambocab** [comment]
Hey, sorry to let this sit a couple days. Is this ready to merge, or did you need to finish checking what happened?

**Comment by pauloricardomg** [comment]
The ticket just got reviewed with +1, would you mind closing the ticket after merging?
https://issues.apache.org/jira/browse/CASSANDRA-10459
Thanks!

**Comment by mambocab** [comment]
Awesome, thanks! (for the record, Ariel Weisberg +1'd this).

Merging.

**Pull request merged**
