### PR TITLE
Add bootstrap test with -Dcassandra.write_survey and nodetool join

### PR DESCRIPTION
**Pull request by ptnapoleon**
Replacing #902 with this

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Rebased, now addressing nits

**Comment by ptnapoleon** [comment]
@pauloricardomg and @mambocab can you review

**Comment by pauloricardomg** [comment]
+1, I think this can be commited since it was already reviewed before and nits addressed.

but I really don't know why we don't enable these bootstrap tests for vnodes, so I created this [branch](https://github.com/riptano/cassandra-dtest/tree/vnodes_bootstrap) enabling these tests for vnodes and will run them through the multiplexer to see if some flakiness will arise due to the data size comparisons.

**Comment by pauloricardomg** [comment]
submitted here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/152/

**Comment by pauloricardomg** [comment]
hmm, multiplexer results didn't look very good, so there's a reason why this is enable only for `@no_vnodes`, so let's keep it the way it is for now (will maybe try to refactor later)
+1

**Pull request merged**
