### PR TITLE
Fix ttl tests about time precision on GCE

### PR DESCRIPTION
**Pull request by aboudreault**

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Do we want to test this on gce first? The changes seem reasonable, and I'm +1.

**Comment by aboudreault** [comment]
If no objection, I don't think it is worth testing it on gce manually. I think failures will be fixed with these changes.

**Comment by ptnapoleon** [comment]
No objection. I trust your judgment.

**Comment by ptnapoleon** [comment]
I'm pulling this in so I can run tests with the changes on cassci

**Pull request merged**
