### PR TITLE
don't manually calculate set() and Counter()

### PR DESCRIPTION
**Pull request by mambocab**
Small thing to improve that I found while filing a bug. @ptnapoleon and/or @knifewine to review.

### CODE REVIEW

**Comment by knifewine** [comment]
hey, collections.Counter is neato.

looks there's another repeat of the same counting logic below (line ~220). if that one's easy to attack we may as well fix both?

i'm +1 on fixing just this one, and also +1 on fixing both.

**Comment by knifewine** [comment]
looks like travis is upset about extra empty lines.

**Comment by mambocab** [comment]
Good catches, thanks.

**Comment by mambocab** [comment]
Can I get a re-review? I think travis should be happy this time.

**Comment by knifewine** [comment]
+1

**Comment by mambocab** [comment]
Thanks, merging.

**Pull request merged**
