### PR TITLE
remove jmxmetrics_test.py

### PR DESCRIPTION
**Pull request by mambocab**
It looks like this test was added, then immediately skipped because it fails. According to Philip, it depends on a number of incorrect assumptions about metrics. We get no value from this, so let's delete it?

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+10

**Comment by mambocab** [comment]
Thanks, Philip. I guess we don't need to wait on Travis?

**Comment by jkni** [comment]
Belated +1. This has been around long enough without being fixed that the collective cost of people rediscovering it outweighs the progress it has made toward a comprehensive test for JMX metrics.

**Comment by ptnapoleon** [comment]
It made only backwards progress, except possibly a string based list of all the metrics, which is trivially locatable

**Pull request merged**
