### PR TITLE
Adjust expected trace output

### PR DESCRIPTION
**Pull request by ptnapoleon**
I still have to check with a dev that this change is intentional, but it definitely doesn't seem accidental.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
No one will answer me on #dev and I can't find the change in Jira.

**Comment by ptnapoleon** [comment]
@mambocab thoughts?

**Comment by ptnapoleon** [comment]
Found it in CASSANDRA-9479

**Comment by mambocab** [comment]
Well now we've got problems
And I think rebasing can solve them

**Comment by mambocab** [comment]
Looks good, consistent with the description in the ticket. +1.

**Pull request merged**
