### PR TITLE
Change all instances of cursor to session

### LINKED ISSUE #402: make "connection" name consistent in codebase and across tests
We've got variables and methods with a soup of variations of session/connection/cursor.

We should try and settle on a single name, preferably the same one used in the cassandra python driver, and make it consistent across dtest.

I think some of this is vestigial from dbapi2 which offered somewhat different abstraction.

### PR DESCRIPTION
**Pull request by ptnapoleon**
Fixes #402.

Cassci results here: http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/connection-rename-dtest/1/testReport/

### CODE REVIEW

**Comment by ptnapoleon** [comment]
@knifewine to review.

@aboudreault or @mambocab to look as well

**Comment by aboudreault** [comment]
+1 for sure on this. "session" is a better name.

**Comment by ptnapoleon** [comment]
Justification for new name: http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Session

**Comment by ptnapoleon** [comment]
CONTRIBUTING.md also altered to reflect this new, hard requirement.

**Comment by mambocab** [comment]
In principle, I love it. However, it looks like there are some problems with the bucketizer right now, so some of the tests aren't getting run:

``` bash
$ nosetests --collect-only --with-id -vv --test-select-config conf/trunk_test-select.cfg 2>&1 |  wc -l
728
```

vs. the `502 + 165 + 2 = 669` that actually got run on CassCI. It's up to you if you want to merge now and deal with any potential fallout once the bucketizer starts working correctly on trunk, but if it were me I'd wait until I could run all the tests on trunk.

**Comment by ptnapoleon** [comment]
I'm aware the auth tests didn't run. I'll run them locally?

**Comment by ptnapoleon** [comment]
Also, I'll add a second commit to fix the travis complaints

**Comment by mambocab** [comment]
Sounds good -- if you run the tests that didn't run locally, this gets an unqualified +1 from me (though, are the auth_tests the only ones that didn't run?). And making Travis happy is a nice onus, thanks for taking that on.

**Comment by knifewine** [comment]
Overall looks good to me. What do you guys think about renaming the connection methods in dtest.py as well (I think they all return session objects), so no reason to cling to "connection" either unless I'm missing something.

**Comment by ptnapoleon** [comment]
I don't mind the current method names. There does seem to be no need for `cql` in the method names anymore, now that the default connection type is native.

**Comment by knifewine** [comment]
+1 with or without the "cql"/"connection" change.

**Comment by mambocab** [comment]
I'm still +1 on this PR without the `cql`/`connection` change, but I do think that we should remove `cql` and change `connection` to `session` at some point. We could do that as part of tackling #204, but I don't think it's a priority.

**Comment by ptnapoleon** [comment]
auth_tests are passing

**Comment by ptnapoleon** [comment]
@mambocab to review the nine thousand pep8 fixes I just made

**Comment by mambocab** [comment]
I left some comments about reformatting multi-line strings, which I'm ambivalent about. I won't hoot and holler about the existing changes getting merged, but I'm meh on pretty much every solution to it.

But the rest of the PEP8 fixes are gorgeous.

**Pull request merged**
