### PR TITLE
bounce cluster post-startup on cl-replaying tests

### PR DESCRIPTION
**Pull request by mambocab**
Should address [CASSANDRA-11811](https://issues.apache.org/jira/browse/CASSANDRA-11811). I'll run CI, if it runs clean I'll get Joel to review.

### CODE REVIEW

**Comment by mambocab** [comment]
Welp, doesn't work:

http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/327/testReport/node_0_iter_001.cdc_test/TestCDC/test_cdc_data_available_in_cdc_raw_2/

@jkni Looks like I'm doing this wrong; do you have suggestions?

**Comment by ptnapoleon** [comment]
I assume there is a step missing before the drain, where-in we wait for the cluster to "settle"?

**Comment by jkni** [comment]
The problem was that it turns out these mutations happen on every start sequence, so bouncing the node didn't solve the problem. Instead, I tried a patch that simply ensures we advance past these commitlog segments [here](https://github.com/jkni/cassandra-dtest/tree/cdc-test-fix).

A parameterized dtest run showed no failures [here](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/329/), so that may be a good approach. What do you think?

**Comment by mambocab** [comment]
Looks like a good approach. I'll pull it out into utility functions and file a PR.

**Comment by mambocab** [comment]
Closing in favor of #1349.

**Pull request closed without merging**
