### PR TITLE
documents purpose of replica_availability_test

### PR DESCRIPTION
**Pull request by mambocab**
addresses #389. Can you review, @ptnapoleon?

### CODE REVIEW

**Comment by ptnapoleon** [comment]
I would specify that it should work with quorum, rather than the more ambiguous "without all nodes up"

**Comment by mambocab** [comment]
@ptnapoleon thank you. Does it look good now?

**Comment by ptnapoleon** [comment]
+1

**Comment by mambocab** [comment]
Thanks, merging.

**Pull request merged**
