### PR TITLE
add test for paging on tables without clustering columns

### PR DESCRIPTION
**Pull request by blerer**

### CODE REVIEW

**Comment by mambocab** [comment]
These look good and pass on the branches linked at CASSANDRA-11208. I'll mark it as awaiting commit, but could you please rebase onto master, and add a small description of the test and the expected C\* behavior in the new test's docstring? Thanks

**Comment by blerer** [comment]
CASSANDRA-11208 has been committed.

**Comment by ptnapoleon** [comment]
Can you rebase? If not, one of us will.

**Comment by blerer** [comment]
Rebased.

**Comment by mambocab** [comment]
Great, thank you! Passes on trunk, merging.

**Pull request merged**
