### PR TITLE
Tests for CASSANDRA-8502

### PR DESCRIPTION
**Pull request by thobbs**

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Why put this here and not in paging_tests.py?

**Comment by ptnapoleon** [comment]
Other than moving this to paging_tests.py, can you change the `@since` annotation to read `2.0.6`, since that is when static columns were introduced?

Other than that, +1. I'll add the doxygen tags myself after merge.

**Comment by thobbs** [comment]
Okay, should be good to go.

**Comment by ptnapoleon** [comment]
+1.

**Pull request merged**
