### PR TITLE
Sstable popen

### PR DESCRIPTION
**Pull request by mambocab**
This should enable debugging for [CASSANDRA-12137](https://issues.apache.org/jira/browse/CASSANDRA-12137). Depends on https://github.com/pcmanus/ccm/pull/510/files for proper error handling, so don't merge yet.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Lgtm, +1

**Comment by knifewine** [comment]
nice! +1

**Comment by ptnapoleon** [comment]
Bump

**Comment by mambocab** [comment]
Thanks. Ran the whole file locally, merging.

**Pull request merged**
