### PR TITLE
Metadata wrapper tests

### PR DESCRIPTION
**Pull request by mambocab**
Adds tests for `metadata_wrapper` in advance of some changes I want to make for [CASSANDRA-12456](https://issues.apache.org/jira/browse/CASSANDRA-12456).

### CODE REVIEW

**Comment by mambocab** [comment]
Whoever wants to review, hold off a minute -- I want to write a couple contract tests.

**Comment by mambocab** [comment]
Never mind. The failures we'll see if contracts are broken will be just as clear as the failing contract tests :+1:

**Comment by mambocab** [comment]
_sigh_ Don't merge. The class I deleted is actually used somewhere.

**Comment by mambocab** [comment]
Ready for review. The affected tests, `cql_tests.py:StorageProxyCQLTester.type_test` and `meta_tests/utils_test/metadata_wrapper_test.py`, pass on my machine.

**Comment by ptnapoleon** [comment]
Afaict, every test looks like it is testing what it says it is. These tests also seem to cover the features of the metadata wrappers that I can think of. I think that's the best +1 you're going to get from me?

**Comment by mambocab** [comment]
Awesome, thanks. Merging.

**Pull request merged**
