### PR TITLE
Fix infinite loop in 2i tests

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab et al to review

### CODE REVIEW

**Comment by mambocab** [comment]
I'd prefer the time-checking part be executed as an assertion in the loop. If I read this correctly, after 30s, the loop will exit, whether the index is built or not. The test should error out in that case.

**Comment by ptnapoleon** [comment]
That is a great idea. I'd rather merge this as-is, and then fix all instances of this loop logic to the new logic in a second PR, that has CI run on it. I admit this is bad practice, but I really want this fix in ASAP

**Comment by knifewine** [comment]
while/else might be a way to go as well

**Comment by ptnapoleon** [comment]
Oh clever, thanks Russ

**Pull request merged**
