### PR TITLE
Write to fresh CLs

### PR DESCRIPTION
**Pull request by mambocab**
Supercedes #1340, implementing @jkni's suggested approach with a shared utility function. @jkni can you review?

### CODE REVIEW

**Comment by mambocab** [comment]
I'll get this running on CI.

**Comment by mambocab** [comment]
CI here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/330/

**Comment by mambocab** [comment]
Whoops, CQL syntax errors. Re-running CI here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/338/

**Comment by stef1927** [comment]
I tested this P.R. with the patch of [CASSANDRA-12509](https://issues.apache.org/jira/browse/CASSANDRA-12509) applied, which will recycle the commit log segments on shutdown, therefore causing commitlog segments to be reliably archived.

For this p.r. to work, we shouldn't restart the node twice because that will generate new tokens, which are saved in a new commitlog segment. See 3803c2b0d3791daa43181e362dba816bf3b5429d, prior to 12509 we should drain the node, but restarting it will cause problems.

**Comment by mambocab** [comment]
Great catch, thanks Stefania! I've cherry-picked your commit and started runs against the 12509 branches:

- [trunk](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/340/)
- [3.0](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/341/)

If they pass, I'll mark this PR as blocked on 12509 and clean up the commented-out code and the commit history. That seem reasonable @stef1927/@jkni?

**Comment by jkni** [comment]
That seems reasonable - if we clean up the commented-out code as no longer relevant, we can also remove some tests from the class. There are a few tests that differ only in their handling of archiving active commitlogs.

**Comment by mambocab** [comment]
Good catch, thanks for the review.

**Comment by stef1927** [comment]
Thanks for running the tests. I've committed 12509 so that it is no longer in the way of this pull request. 12509 only applies to 3.0+ but calling drain should be sufficient for earlier versions.

There is still one[ failing test](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/341/testReport/junit/node_1_iter_008.snapshot_test/TestArchiveCommitlog/test_archive_commitlog_point_in_time_with_active_commitlog_ln/), maybe we should flush before checking that there is at least one commit log backed up that is not one of the active commit logs?

**Comment by mambocab** [comment]
Thanks for the reviews. Rerunning here:

- [3.0](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/344/parameters/)
- [trunk](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/343/parameters/)

If those look good I'll ask for one more review and merge after that.

**Comment by mambocab** [comment]
Sorry for the latency on this one. The tests ran clean, and this, surprisingly, is still mergable. @jkni and/or @stef1927 Could you please review again?

**Comment by stef1927** [comment]
+1, LGTM

**Comment by mambocab** [comment]
Thank you! Merging.

**Comment by krishnajinka** [comment]
Hello, I was following this issue from jira: https://issues.apache.org/jira/browse/CASSANDRA-11811?jql=text%20~%20%22CassandraDaemon.java%20Cannot%20change%22
. We are using 3.11.2 and i see this error in the log while starting the cassandra, and it fails. I read the jira and understood that mutation happens, thereby doubling the number of tokens, and hence due to mismatch 

INFO  [main] [2020-05-28 11:05:14] OutboundTcpConnection.java:108 - OutboundTcpConnection using coalescing strategy DISABLED
INFO  [HANDSHAKE-/192.168.5.53] [2020-05-28 11:05:14] OutboundTcpConnection.java:560 - Handshaking version with /192.168.5.53
INFO  [main] [2020-05-28 11:05:15] StorageService.java:707 - Loading persisted ring state
INFO  [main] [2020-05-28 11:05:15] StorageService.java:825 - Starting up server gossip
INFO  [main] [2020-05-28 11:05:15] TokenMetadata.java:479 - Updating topology for /192.168.5.52
INFO  [main] [2020-05-28 11:05:15] TokenMetadata.java:479 - Updating topology for /192.168.5.52
Cannot change the number of tokens from 512 to 256
Fatal configuration error; unable to start server.  See log for stacktrace.
ERROR [main] [2020-05-28 11:05:15] CassandraDaemon.java:708 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot change the number of tokens from 512 to 256
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:989) ~[apache-cassandra-3.11.2.jar:3.11.2]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:682) ~[apache-cassandra-3.11.2.jar:3.11.2]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:613) ~[apache-cassandra-3.11.2.jar:3.11.2]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:379) [apache-cassandra-3.11.2.jar:3.11.2]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602) [apache-cassandra-3.11.2.jar:3.11.2]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.2.jar:3.11.2]
INFO  [StorageServiceShutdownHook] [2020-05-28 11:05:15] HintsService.java:220 - Paused hints dispatch
INFO  [StorageServiceShutdownHook] [2020-05-28 11:05:15] Gossiper.java:1540 - Announcing shutdown
INFO  [StorageServiceShutdownHook] [2020-05-28 11:05:15] StorageService.java:2292 - Node /192.168.5.52 state jump to shutdown
INFO  [HANDSHAKE-/192.168.5.53] [2020-05-28 11:05:15] OutboundTcpConnection.java:560 - Handshaking version with /192.168.5.53

I want to know if the fix for this issue is available in 3.11.2 .

**Pull request merged**
