### PR TITLE
Adds smoke tests for cqlsh

### PR DESCRIPTION
**Pull request by mambocab**
These aren't comprehensive tests, but they add basic coverage. I used the titles of the stubbed [cqlsh parsing tests in C* trunk](https://github.com/apache/cassandra/blob/trunk/pylib/cqlshlib/test/test_cql_parsing.py) as a starting point.

I may have found a bug in pre-trunk releases with [CREATE INDEX](https://github.com/riptano/cassandra-dtest/blob/b712395bc318ab41b26762ba395e3866ac36f4be/cqlsh_tests.py#L749) and [DROP INDEX](https://github.com/riptano/cassandra-dtest/blob/b712395bc318ab41b26762ba395e3866ac36f4be/cqlsh_tests.py#L776) handling. I think they may just be bugs in the cqlsh parser. I've marked the tests for these statements `@since('3.0')` until I can isolate the bug.

Pinging @thobbs in case he wants to have a look.

### CODE REVIEW

**Comment by thobbs** [comment]
The tests look like a good start to me!

**Comment by ptnapoleon** [comment]
@mambocab What's the status on these?

**Comment by mambocab** [comment]
I've filed the bug I found [here](https://issues.apache.org/jira/browse/CASSANDRA-9247) and changed the `@since('3.0')` to `@since('2.1')` now that I understand the bug better.

Since Tyler approves, I'm just waiting on a +1 from someone else in TE.

**Comment by ptnapoleon** [comment]
His +1 is good enough for me. But just in case, I also think it looks good, +1.

**Pull request merged**
