### PR TITLE
updated log statement for CASSANDRA-12532

### PR DESCRIPTION
**Pull request by clohfink**

### CODE REVIEW

**Comment by mambocab** [comment]
Thanks for the PR! This will need to be version-gated -- I assume this is targeting 3.10?

I can make the version-gating changes if you like -- just let me know.

**Comment by mambocab** [comment]
Post-Summit ping @clohfink -- you want me to take this over for version-gating, or are you good for it?

**Comment by thobbs** [comment]
@mambocab do you mind taking care of the version gating?

**Comment by mambocab** [comment]
Yeah, happy to; sorry to let this sit.

**Comment by mambocab** [comment]
Replaced by #1339; closing.

**Pull request closed without merging**
