### PR TITLE
Harden restart_node_test

### PR DESCRIPTION
**Pull request by ptnapoleon**
See discussion in CASSANDRA-10870

@mambocab or @stef1927 to review. We'll give this a week or so after merging to see if the flapping tests start passing on CI, before we resolve 10870.

### CODE REVIEW

**Comment by mambocab** [comment]
Code looks good, but I'd wait on a review from @stef1927 as well.

**Comment by mambocab** [comment]
Ping @stef1927 -- could you have a look, please? Thanks.

**Comment by stef1927** [comment]
Sorry I missed the initial ping. LGTM.

**Comment by mambocab** [comment]
:+1: not a problem, that's what pinging is for! Thanks for the review/merge.

**Pull request merged**
