### PR TITLE
Adds a @no_offheap skip test decorator and applies it to index_summary_upgrade

### PR DESCRIPTION
**Pull request by EnigmaCurry**
@mambocab mentioned it is probably a good candidate for porting this test over to the new upgrade framework, but for now I just disabled this test for offheap runs as I don't see any offheap considerations here, and the upgrade mechanics here are already pretty manual.

### CODE REVIEW

**Comment by mambocab** [comment]
Thought I commented on this, but apparently not. The code itself is fine, but I don't see any reason not to solve this problem by feature-gating the 2.0 part of the test.

**Comment by mambocab** [comment]
Ping @EnigmaCurry

**Comment by ptnapoleon** [comment]
@mambocab Clean this up?

**Comment by mambocab** [comment]
Yeah, I can take this.

**Comment by mambocab** [comment]
Ah, looks like this was addressed in #801. @mshuler can you confirm?

I don't think the fix implemented in this PR is the best solution anyway, so I'l close.

**Pull request closed without merging**
