### PR TITLE
Add version check when creating second index on map column

### PR DESCRIPTION
**Pull request by beobal**
For CASSANDRA-11186

### CODE REVIEW

**Comment by ptnapoleon** [comment]
+1

**Comment by ptnapoleon** [comment]
-1. The value of `self.UPGRADE_PATH.upgrade_version` can be in the form `git:cassandra-2.2`, and thus the comparison logic there doesn't work. You will need to first make sure it is in the right form.

**Comment by beobal** [comment]
ah yes, are there util methods anywhere for normalizing versions that way? Or if not, a way to test the version of the specific session (rather than the cluster)?

**Comment by mambocab** [comment]
Apologies for the really roundabout API, but here's an example:

https://github.com/riptano/cassandra-dtest/blob/master/upgrade_tests/cql_tests.py#L377

```
if self.get_node_version(is_upgraded) >= '2.2':
```

**Comment by beobal** [comment]
Thanks Jim. I've made that change, rebased, squashed/merged & pushed to master.

**Comment by mambocab** [comment]
Awesome, thank you :tada:

**Pull request closed without merging**
