### PR TITLE
Add test for thrift accessing a compact storage created table.

### PR DESCRIPTION
**Pull request by JeremiahDJordan**
This current fails on cassandra-3.0 branch.

### CODE REVIEW

**Comment by mambocab** [comment]
Thanks for the test -- can you please address the linter errors found with CI?

Could you briefly explain how this tests COMPACT STORAGE on 3.0? My understanding was that there is no compact storage anymore.

**Comment by JeremiahDJordan** [comment]
It does a "create table ... with compact storage" and then inserts and reads from the table using thrift.  There isn't a different storage format on disk any more, not sure if the "with compact storage" does anything or not under 3.0, but for the test to work under C* 2.1/2.2 it is needed...

**Comment by JeremiahDJordan** [comment]
(This test passes on 2.1/2.2 and causes an exception on 3.0) https://issues.apache.org/jira/browse/CASSANDRA-10586

**Comment by mambocab** [comment]
Gotcha -- yeah, I'm pretty sure WITH COMPACT STORAGE is a noop in 3.0.

Is it all right if I merge this, then make CASSANDRA-10586 a subtask of CASSANDRA-10166, our ticket for tracking all failing 3.0 tests?

**Comment by JeremiahDJordan** [comment]
SGTM

**Comment by mambocab** [comment]
Great, will do. Thanks for making the changes for the linter and explaining the test.

**Pull request merged**
