### PR TITLE
Test for CASSANDRA-9673

### PR DESCRIPTION
**Pull request by stef1927**
Tests for batched logs and mixed version clusters (CASSANDRA-9673).

### CODE REVIEW

**Comment by stef1927** [comment]
@ptnapoleon, @mambocab - could you please review when you can?

**Comment by ptnapoleon** [comment]
For one, you can remove all the of `require` annotations, since 9673 was committed.

**Comment by ptnapoleon** [comment]
I see nothing wrong. Jim?

**Comment by mambocab** [comment]
Yep, looks good. Un`require` and merge, as far as I'm concerned. Thanks!

**Comment by stef1927** [comment]
Thanks for the review, un-required and merged.

**Pull request merged**
