### PR TITLE
adds information on py3 division to CONTRIBUTING

### PR DESCRIPTION
**Pull request by mambocab**
This is follow up for [a comment I left on a PR today](https://github.com/riptano/cassandra-dtest/pull/371#discussion_r34169469). Related to #84.

### CODE REVIEW

**Comment by mambocab** [comment]
@aboudreault This is low-priority, but small; when you get a chance could you please review?

**Comment by aboudreault** [comment]
+1 Jim. I think we should create a ticket to also include absolute_import and unicode_literals. Thoughts?

**Comment by mambocab** [comment]
As in, "new files should use absolute_imports and unicode_literals where applicable"? I'd be +1 on that. Any reason not to tack it on to this PR?

**Comment by aboudreault** [comment]
yep. We can add a note in this PR for sure. The issue is more for all existing files. (When we have time to do it and test properly, so mostly after 3.0 release?)

**Comment by mambocab** [comment]
I've pushed up a note about them -- it's pretty minimal. I'll add a note to the Python 3 issue. Any objections or clarifications you want, @aboudreault?

**Comment by aboudreault** [comment]
All good my friend!

**Comment by mambocab** [comment]
:+1: thanks!

**Pull request merged**
