### PR TITLE
Increased TestCommitLog.small_segment_size_test error tolerance from 20% to 25%

### PR DESCRIPTION
**Pull request by pauloricardomg**
Fix for CASSANDRA-10098

### CODE REVIEW

**Comment by pauloricardomg** [comment]
Needs to be validated here: https://issues.apache.org/jira/browse/CASSANDRA-10098

**Comment by mambocab** [comment]
@pauloricardomg was this ready to be committed? I don't see anything at CASSANDRA-10098 indicating you'd figured it out.

**Comment by pauloricardomg** [comment]
@mambocab not really, but since @aboudreault is the original author of the test, I assumed the merge was a validation, unless there was some confusion there.

**Comment by aboudreault** [comment]
Yeah, the tolerance increase is fine as soon as it fixes the issue. Hopefully, we won't have to increase it again, otherwise we'll have to write a test more deterministic.

**Comment by mambocab** [comment]
Ah, I understand, sorry. Thanks for confirming!

**Pull request merged**
