### PR TITLE
Tests for CASSANDRA-9399

### PR DESCRIPTION
**Pull request by stef1927**
These are the tests for [CASSANDRA-9399] (https://issues.apache.org/jira/browse/CASSANDRA-9399), which was committed yesterday.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
@mambocab to review

**Comment by mambocab** [comment]
+1! Thanks, @stef1927.

**Comment by stef1927** [comment]
Thanks guys!

**Comment by ptnapoleon** [comment]
This seems to have become impossible to merge. @stef1927 can you resolve the conflicts with master? Then feel free to merge the PR in.

**Comment by stef1927** [comment]
I rebased with master but I cannot merge myself.

**Pull request merged**
