### PR TITLE
Expand docstring comments for the auth tests.

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab and @knifewine to review.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
If you're wondering why I changed all the assertions that check we have no permissions set, from comparing len() == 0 to comparing sets, is to improve debug output.

Previously if the tests failed, it would just say "Expected 0 rows, got X" where X is an int. Now it will say "Expected 0 rows, found X", where X are the actual rows pulled from C*.

**Comment by mambocab** [comment]
My comment on `prepare()` applies everywhere it's described as `launch a one-node cluster`. It's a little nit, but it should be pretty easy to clean up too, so I think you should hold merge on fixing it.

**Comment by mambocab** [comment]
Logging off, but I just wanted to note that I've reviewed through to `create_ks_auth_test`.

**Comment by ptnapoleon** [comment]
@knifewine do you have bandwidth to resume Jim's review?

**Comment by ptnapoleon** [comment]
The newest commit about your desire for namedtuples breaks everything [specifically the assertions]? Is there a more correct way to make these into namedtuples? If not, why did you want that?

**Comment by knifewine** [comment]
+1

**Pull request merged**
