### PR TITLE
Add paging tests for filtering with clustering columns for 11310

### PR DESCRIPTION
**Pull request by ifesdjeen**
Add paging tests for filtering with clustering, static and regular columns for [#11310](https://issues.apache.org/jira/browse/CASSANDRA-11310)

### CODE REVIEW

**Comment by ptnapoleon** [comment]
All of the since annotations need to be `@since('3.6')` not `@since('3.6.0')`. Trunk currently evaluates to `3.6`, which nose evaluates to being less than `3.6.0`, meaning these won't run on the correct versions.

**Comment by ptnapoleon** [comment]
Otherwise, +1

**Comment by ifesdjeen** [comment]
@ptnapoleon my bad, going to fix that right away.

**Comment by ifesdjeen** [comment]
Fixed. I'll post here whenever the #11310 is merged.

**Comment by blerer** [comment]
CASSANDRA-11310 has been committed.

**Pull request merged**
