### PR TITLE
Additional test coverage for CASSANDRA-10238

### PR DESCRIPTION
**Pull request by stef1927**
I've expanded the test for CASSANDRA-10238 as follows:

- cover 3 all snitches capable of updating their configuration file
- multi-dc setup
- test adding new racks

See CASSANDRA-10238 for further details.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Lgtm, @mambocab? There are a few pep8 complaints from travis, though.

**Comment by mambocab** [comment]
LGTM too, after fixing linter warnings. @knifewine might be a better reviewer for this, though.

**Comment by knifewine** [comment]
very minor nit, we should rename wait_for_all_nodes_on_rack to something like: wait_for_nodes_on_racks since it has changed a litt bit.

nit aside, looks fantastic, +1

**Comment by stef1927** [comment]
Thanks for your comments, I've renamed wait_for_all_nodes_on_rack to wait_for_nodes_on_racks and fixed the travis complaints.

**Pull request merged**
