### PR TITLE
CASSANDRA-12039

### PR DESCRIPTION
**Pull request by beobal**
Supercedes PR #1170

### CODE REVIEW

**Comment by ptnapoleon** [comment]
(1) This still needs rebased
(2) Can I see a clean CI run? Did you fix the hanging dtest issue?

**Comment by beobal** [comment]
(1) heh, it didn't when I pushed it a half hour ago. It's re-rebased now
(2) I did fix the hanging dtest, but realise I haven't put that through CI only tested locally. So I've kicked off 3.0 & trunk dtest jobs and linked them from JIRA.

**Comment by ptnapoleon** [comment]
Your since annotations should be `3.0.9`, not `3.0`, and -1, because resume_test is still hanging on CI

**Comment by ptnapoleon** [comment]
Thoughts on fixing resume test?

**Comment by beobal** [comment]
@ptnapoleon am I good to merge this now? I've modified the annotations, adding the `@skipIf` and switching `@since` to `3.10` as this is now only going to trunk. 

Latest CI result contains 1 failure, which seems unrelated & passes for me locally. http://cassci.datastax.com/view/Dev/view/beobal/job/beobal-12039-trunk-dtest/2/

**Comment by ptnapoleon** [comment]
+1, merge away

**Pull request merged**
