### PR TITLE
Include quoted index names in describe test

### PR DESCRIPTION
**Pull request by beobal**
See CASSANDRA-12847

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Is there a compelling reason that this is here, and not in cqlshlib tests? Patch LGTM, except will this still work on 2.1?

**Comment by ifesdjeen** [comment]
I've [trigged a CI on branch](https://issues.apache.org/jira/browse/CASSANDRA-12847) to make sure.

**Comment by beobal** [comment]
> Is there a compelling reason that this is here, and not in cqlshlib tests? 

Only that the DESCRIBE test is already here and the cqlshlib tests are more focused on the layout and stying, rather than content.

> Patch LGTM, except will this still work on 2.1?

That's a good point. I've pushed a second commit to ensure that we only expect the new behaviour on 3.0.11+ and 3.10+

**Comment by ptnapoleon** [comment]
Is this ready to merge, @beobal ?

**Comment by ifesdjeen** [comment]
Not yet, waiting for Cassandra ticket to get committed, shortly!

**Comment by beobal** [comment]
sorry, I missed the notifications for this PR. It needed a rebase as pretty much all tests were failing against trunk due to an outdated version of ccm. I've done that, force pushed, and kicked off one more round of CI. When that's happy I'll commit the C* ticket & merge this.  Apologies again for the latency :)

**Comment by ptnapoleon** [comment]
Bump, @beobal ?

**Comment by ifesdjeen** [comment]
CI looks good now, just giving heads up!

**Comment by beobal** [comment]
@ptnapoleon the C* ticket has been committed now, so cqlsh_tests will fail on 3.0+ until this is merged.

**Pull request merged**
