### PR TITLE
Fix commitlog replay test

### PR DESCRIPTION
**Pull request by mambocab**
DON'T MERGE UNTIL WE'VE UPDATED DEPENDENCIES IN OUR INSTALL SCRIPTS.

I have a few concerns about this one.

- @ptnapoleon Could you please run this test on Windows to make sure `parse` behaves the way we expect?
- I'm worried about the change in SSTable-grabbing code -- I don't think there was a reason to write custom to grab SSTables. Can someone confirm?

I'm actually quite happy with the way the log-checking code turned out. Of course, please have a good hard look at it. Asking for reviews from both @ptnapoleon and @knifewine please.

### CODE REVIEW

**Comment by mambocab** [comment]
For an explanation of why the log-checking code needed to change, read the commit message.

**Comment by mambocab** [comment]
Travis is mad, but it's unrelated:

```
$ flake8 --ignore=E501,F811,F812,F821,F822,F823,F831,F841,N8,C9 --exclude=thrift_bindings,cassandra-thrift .
./cqlsh_tests/cqlsh_copy_tests.py:28:1: F401 'known_failure' imported but unused
./cqlsh_tests/cqlsh_copy_tests.py:29:1: F401 'skip' imported but unused
```

**Comment by mambocab** [comment]
Made PR for the `parse` dependency:

https://github.com/riptano/cassandra-jenkins-util/pull/4

**Comment by mambocab** [comment]
> I don't think there was a reason to write custom to grab SSTables

I should rephrase: I don't think there's a reason to maintain custom code for this anymore.

**Comment by ptnapoleon** [comment]
Runs fine on windows, and I am +1

**Comment by knifewine** [comment]
can we confirm the test runs ok on 2.1.x, 2.2.x, 3.0.x, 3.x, and trunk?

if those look good, I'm +1

**Comment by mambocab** [comment]
> can we confirm the test runs ok on 2.1.x, 2.2.x, 3.0.x, 3.x, and trunk?

Ran on HEAD and most recent release for each of those series, passes locally. Really good suggestion, thanks.

Will merge the dependency PR, then this.

**Pull request merged**
