### PR TITLE
add large attribute to test methods

### PR DESCRIPTION
**Pull request by smccarthy788**
@ptnapoleon, @mambocab, please review.

### CODE REVIEW

**Comment by mambocab** [comment]
It worries me that Travis doesn't see the problem here -- you need to import `nose.plugins.attrib.attr` before using it.

**Comment by mambocab** [comment]
Does trying to import the changed modules work?

**Comment by mambocab** [comment]
Also:

\*rap air horns\* **BIKESHED TIIIIIME**

@ptnapoleon @knifewine is `large` the name we want to use for this class of test? We could also do something like `many-nodes` or `large-instance-size`.

**Comment by ptnapoleon** [comment]
Do we need it to be more specific than large? I don't care between the choices presented, honestly

**Comment by mambocab** [comment]
I'm of 2 minds. We don't want vocabulary that only people in DS TE understand, but we also don't want need to be completely explicit all the time. I think I'm +0.5 for a longer one, no real preference between the longer options. @knifewine tiebreaker?

**Comment by knifewine** [comment]
Yeah, 'large' is pretty ambiguous. I lean towards large-instance-size, but it's still a bit confusing since tests can may get run locally by people in which case 'instance' is a weird word too.

**Comment by knifewine** [comment]
large-instance-size or maybe resource-intensive-test ?

**Comment by mambocab** [comment]
I like `resource-intensive`. Any objections to having Sean use that?

**Comment by ptnapoleon** [comment]
+1 to resource-intensive

**Comment by mambocab** [comment]
Cool. This needs to be rebased but then we can merge :+1:

**Comment by ptnapoleon** [comment]
+1

**Pull request merged**
