### PR TITLE
Fix pep8 2015 01 18

### PR DESCRIPTION
**Pull request by lmr**
A few PEP8 fixes necessary for the PEP checks to only ignore E501 errors.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
@mambocab I'll let you handle review here, specifically the travis changes. It all LGTM though.

**Comment by mambocab** [comment]
+1 on the PEP8 and `travis.yml` changes. I'm not comfortable with introducing another local linting script, though. Personally I think I'd prefer keeping only the existing shell script, but I never use the local linting script. @aboudreault You wrote and use the local script -- do you have any feelings about it? I strongly want to avoid maintaining 2 linting scripts, and less strongly feel we should avoid introducing a dependency on `inspektor`.

**Comment by aboudreault** [comment]
From my point of view, I don't see any problem modifying/improving our existing linter script but I wouldn't introduce a new one. @lmr @mambocab , I agree with Jim about the new dependency.. do we really need anything else than pep8 and flake8?

**Comment by lmr** [comment]
@mambocab @aboudreault It's really an optional script. If you guys don't like it, I can simply remove that commit from this Pull Request.

**Comment by lmr** [comment]
There, I've removed the script. Thanks.

**Comment by mambocab** [comment]
@lmr Yeah, I think that's appropriate here. Sorry to reject the script, but thank you for the suggestion. I'll check out `inspektor` one of these days, but today is not that day.

Thank you for your help; it's nice that we'll be able to be a stricter with our linting going forward. We appreciate it! Merging.

**Comment by lmr** [comment]
@mambocab no worries, I sent the PR with the commit knowing it'd be controversial. Better to ask for forgiveness than permission, right?

**Comment by mambocab** [comment]
Sure is :)

**Pull request merged**
