### PR TITLE
add uncodified knowledge to CONTRIBUTING

### PR DESCRIPTION
**Pull request by mambocab**
This is some stuff that trips people up but isn't written down anywhere. Is CONTRIBUTING the right place for it? Maybe the README is better; I feel like most people who look at this also contribute tests, and they may be more likely to read the README. Though, this does only pertain to contributing. I'm 100% ambivalent.

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
I'm ambivalent too, but if it goes in CONTRIBUTING, we should probably note that there *is* a CONTRIBUTING doc in the README.

**Comment by ptnapoleon** [comment]
Where do you see a contributing doc in the readme?

**Comment by ptnapoleon** [comment]
I might be wrong, but isn't contributing.md traditionally for non-functional, subjective requirements of the project? These are just straight up tips on how to avoid common test bugs when writing a new test. Those seem like they fit the Readme a lot better.

**Comment by mambocab** [comment]
Philip won me over. I've moved it to the README.

**Comment by EnigmaCurry** [comment]
@ptnapoleon I don't see any reference to contributing in readme. That's what I'm saying, probably a lot of people don't know about contributing because it's not linked in readme.

**Comment by ptnapoleon** [comment]
Oh I parsed your sentence wrong, my bad.

**Comment by ptnapoleon** [comment]
+1

**Pull request merged**
