### PR TITLE
tools reorg and paging dedupe

### PR DESCRIPTION
**Pull request by knifewine**

### CODE REVIEW

**Comment by ptnapoleon** [comment]
nit: contributing.md should refer to the new file locations

**Comment by mambocab** [comment]
It'd be nice to fold `jmxutils` into `tools` as well.

**Comment by knifewine** [comment]
ah, nice catches. moved in jmxutils and also updated contributing.md (hopefully 'subpackage' is the right word there...)

**Comment by ptnapoleon** [comment]
Rather than nit, I pushed a commit with an extra change in CONTRIBUTING

**Comment by knifewine** [comment]
thanks for the commit @ptnapoleon

**Comment by knifewine** [comment]
rebased to get up to date with master, and pushed some new commits to fix import issues and a circular import. I was seeing different test counts between master and this branch which clued me in to the issue.

now when I run nose to collect tests I get the same test count for master as I do for this branch (4867 tests atm).

**Comment by knifewine** [comment]
I think this is ready for a more thorough review now.

**Comment by knifewine** [comment]
friendly ping @mambocab and @ptnapoleon 

rebasing this to keep current is getting kinda painful, can you guys have a look in the near future?

**Comment by ptnapoleon** [comment]
I am +1 on where things were moved, so if CI passes, this is good to merge afaik

**Comment by mambocab** [comment]
Same as @ptnapoleon, sorry for the delay in rereview.

**Comment by knifewine** [comment]
thanks gents.

trying out a CI job here pointed at the dtest branch.

**Comment by knifewine** [comment]
found a couple issues with the first CI job, patched and running another here: http://cassci.datastax.com/view/Dev/view/knifewine/job/trunk_dtest_tools_reorg/2/

**Comment by knifewine** [comment]
CI and travis are happy, merging now. Thanks for the reviews!

**Pull request merged**
