### PR TITLE
upgrade tests to ignore rejected execution exception

### PR DESCRIPTION
**Pull request by knifewine**

### CODE REVIEW

**Comment by knifewine** [comment]
@ptnapoleon to review

**Comment by knifewine** [comment]
oops, make that @mambocab instead.

**Comment by mambocab** [comment]
Code looks fine. The regex is detailed enough to pick up a unique error. I don't know the context, but I trust ya, @knifewine, so merge away, unless you wanted feedback on something else.

**Comment by mambocab** [comment]
> The regex is detailed enough to pick up a unique error

That is, based on my grepping of the C* codebase.

**Comment by knifewine** [comment]
Yeah, I think the main risk here is hiding a legit failure, but I think that's not very probable.

**Comment by ptnapoleon** [comment]
Why are we getting the TPE shut down error?

**Comment by knifewine** [comment]
I think it's a basic refusal to take on a task when cassandra is shutting
down, esp. given Ellis' nonplussed attitude about it on CASSANDRA-7727

On Mon, Aug 3, 2015 at 2:30 PM, Philip Thompson <notifications@github.com>
wrote:

> Why are we getting the TPE shut down error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/riptano/cassandra-dtest/pull/436#issuecomment-127398785>
> .
>



-- 
<http://cassandrasummit-datastax.com/?utm_campaign=summit15&utm_medium=summiticon&utm_source=emailsignature>

**Pull request merged**
