### PR TITLE
Speed up cqlsh copy tests

### PR DESCRIPTION
**Pull request by thobbs**
This should roughly cut the total test run time in half (currently 1hr)

### CODE REVIEW

**Comment by thobbs** [comment]
Actually, I have a couple more changes to push, so hold off on review.

**Comment by thobbs** [comment]
Okay, should be good to review now.  A test run of the full module passes for me locally in ~38 minutes.

**Comment by ptnapoleon** [comment]
Can you rebase, but +1

**Comment by thobbs** [comment]
Rebased and merged, thanks.

**Comment by mambocab** [comment]
breaks the copy tests pre-3.0 :/ reverting.

**Pull request merged**
