### PR TITLE
changes mbean used for querying memtable heap size

### PR DESCRIPTION
**Pull request by mambocab**
Don't merge just yet -- I think this is the correct change, but I'm waiting for confirmation from Benedict [here](https://issues.apache.org/jira/browse/CASSANDRA-9194?focusedCommentId=14505980&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14505980) that this is the right metric to use.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
If benedict confirms, I'm +1

**Comment by ptnapoleon** [comment]
Did Benedict get back to you yet?

**Comment by mambocab** [comment]
No. [Just pinged him](https://issues.apache.org/jira/browse/CASSANDRA-9194?focusedCommentId=14517622&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14517622).

**Comment by mambocab** [comment]
[Benedict has confirmed](https://issues.apache.org/jira/browse/CASSANDRA-9194?focusedCommentId=14523017&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14523017), merging.

**Pull request merged**
