### PR TITLE
Skip broken commitlog tests

### PR DESCRIPTION
**Pull request by mambocab**
More tests broken by 8099. This depends on #376, so it shouldn't be merged yet.

### CODE REVIEW

**Comment by mambocab** [comment]
I'm expanding the scope of this PR to deal with all the `@requires` that need to be merged after #376.

**Comment by mambocab** [comment]
I've fixed merge problems and this is ready for review.

**Comment by mambocab** [comment]
Ah, I forgot to tag a reviewer. @ptnapoleon when you get a chance could you have a look? Thanks.

**Comment by ptnapoleon** [comment]
+1

**Comment by mambocab** [comment]
Thanks!

**Pull request merged**
