### PR TITLE
Harden replication tests

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab to review

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Sorry about the sleep, but nothing I could do about it. There is no programmatic way to check for trace completion effectively.

**Comment by mambocab** [comment]
LGTM. Can you file a PYTHON ticket for the sleep you need?

**Comment by ptnapoleon** [comment]
...No? There is no way to know how long to sleep. So it's not something the driver can add.

**Comment by mambocab** [comment]
buh, sorry -- I meant adding information about when traces were completed. Adam explained over on the PYTHON Jira that that would require a server change and why, though. :+1:

**Pull request merged**
