### PR TITLE
Follow up to #1146

### PR DESCRIPTION
**Pull request by pauloricardomg**
Minor change, basically changed simple_rebuild_test query cl to LOCAL_ONE and remove known_failure annotation

Can you have a look @yukim @mambocab? Thanks!

### CODE REVIEW

**Comment by yukim** [comment]
+1, with CI check fixed. (F401 'tools.known_failure' imported but unused)

**Comment by mambocab** [comment]
LGTM after removing the unused import. Thanks!

**Comment by jkni** [comment]
I think I'm -1 on removing the known_failure here. It looks like we had a failure on nightly CI after #1146 was merged and I can reproduce the failure pretty easily locally. Not sure why the multiplexer run on [CASSANDRA-11687](https://issues.apache.org/jira/browse/CASSANDRA-11687) didn't catch this.

**Comment by mambocab** [comment]
Sorry, yes, my mistake. +1 after removing the deletion of `known_failure`.

**Comment by pauloricardomg** [comment]
closed in favor of #1158

**Pull request closed without merging**
