### PR TITLE
Use schema_wait_session to create UDFs

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab or @knifewine or @smccarthy788. This WILL fix the test, but I'm only 80% sure doesn't change the test in a bad way. Someone sanity check this is reasonable?

### CODE REVIEW

**Comment by mambocab** [comment]
I don't have enough context for this. What's the error?

The implication I'm getting from this, though, is that you have to use a particular session for the `wait_for_schema_agreement` call below this code to successfully block on schema agreement. That sounds like a bug.

**Comment by ptnapoleon** [comment]
I don't think its a bug, so much as a race condition/necessary evil

**Comment by mambocab** [comment]
I still don't follow. The restrictions on blocking on schema agreement are on the session you use to block, not on the session you execute the schema changes from.

**Comment by ptnapoleon** [comment]
Yep, we need someone to confirm if this is a bug or not. Would it be in the driver maybe? @jkni ?

**Comment by ptnapoleon** [comment]
Oh god I've forgotten all the context on this, Jim, let's get back to it on Monday?

**Comment by ptnapoleon** [comment]
From discussion with Joel, this just seems like a python driver limitation. Whether that gets improved or not, I'd like to merge this, please

**Comment by mambocab** [comment]
Fair enough. File a PYTHON ticket and merge IMO.

**Comment by ptnapoleon** [comment]
From Joel's comments, sounds like it is fixed in 3.6.0, so no need.

**Pull request merged**
