### PR TITLE
Clean up Jake's PR

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab to review.

Also fixes Travis complaints

### CODE REVIEW

**Comment by tjake** [comment]
Looks good, there are other instances of this we should fix (I saw some in cqlsh_tests as well)

**Comment by ptnapoleon** [comment]
Yes, but `delete=False` isn't set there.

**Comment by tjake** [comment]
I'm saying we need to put delete=False everywhere

**Comment by mambocab** [comment]
The explicit `unlink`s make me sad, but if that's what fixes it, that's what fixes it. LGTM.

**Pull request merged**
