### PR TITLE
un-ugly exception output on error

### PR DESCRIPTION
**Pull request by knifewine**

### CODE REVIEW

**Comment by knifewine** [comment]
don't review just yet, making a few small tweaks presently

**Comment by knifewine** [comment]
ok, ready for a look @mambocab and @ptnapoleon
part of the problem was string formatting a list in the error message, which didn't ever work I presume.

I tested locally with both end-of-test scanning and the scanning from ENABLE_ACTIVE_LOG_SCANNING. works fine and formats nicely.

**Comment by ptnapoleon** [comment]
I see the change now. Lgtm.

**Comment by knifewine** [comment]
from a ci run: http://cassci.datastax.com/view/Dev/view/knifewine/job/trunk_dtest_stderr_format_scratch/lastCompletedBuild/testReport/index_summary_upgrade_test/TestUpgradeIndexSummary/test_upgrade_index_summary/

**Comment by ptnapoleon** [comment]
+1. Merge away.

**Pull request merged**
