### PR TITLE
Fixed materialized view tests in the context of CASSANDRA-10171

### PR DESCRIPTION
**Pull request by pauloricardomg**
Tests need to be validated before on https://issues.apache.org/jira/browse/CASSANDRA-10171

### CODE REVIEW

**Comment by aboudreault** [comment]
I'll check this PR in details today

**Comment by pauloricardomg** [comment]
@aboudreault could you review? I added more details about the refactoring on the JIRA ticket itself. Thank you!

**Comment by pauloricardomg** [comment]
oops, didn't saw your message before.. seems we had a conflict. thanks! :)

**Comment by tjake** [comment]
The test should fail at CL.ALL since the inconsistency is between the base and MV table not the MV replicas themselves.

**Comment by tjake** [comment]
I mean in the really_complex_repair test.  I guess it's ok to leave it at QUORUM either way.

**Comment by aboudreault** [comment]
LGTM. nice findings about the batchlogs and datacenters. Since number of nodes changed, can you confirm that you tested that all tests was failing accordingly by modifying the test logic?

**Comment by pauloricardomg** [comment]
@aboudreault yep, I did some manual test mutations and verified they failed.

**Comment by aboudreault** [comment]
Excellent. Thanks!

**Pull request merged**
