### PR TITLE
add a forgotten since decorator

### PR DESCRIPTION
**Pull request by knifewine**
@tjake to review.

### CODE REVIEW

**Comment by mambocab** [comment]
See my note [here](https://issues.apache.org/jira/browse/CASSANDRA-11278?focusedCommentId=15183139&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15183139):

> I think a more complex `@since` is necessary – if I understand correctly, the change was merged to 3.0.4 on the 3.0 track, and 3.4 on the tick-tock track.
> Side note – my mistake, I'm the one who forgot to add the decorators.

**Comment by knifewine** [comment]
ok, feel free to close this unless there's any reason to keep it out here. I was basically told 3.4+ only last week for this (but I could see in the code the check method was doing something a bit more involved, hence having a review at all).

**Comment by mambocab** [comment]
Nope, I was wrong, my mistake. This is 3.4+ only.

**Comment by mambocab** [comment]
Which means that the code check method is erroneously complex. Personally I kinda like pulling that logic out into a function with a name. In any event, the function should either be fixed or replaced with an inline comparison to `'3.4'`.

**Comment by knifewine** [comment]
@mambocab, I force pushed changes to remove the extra logic.

**Comment by knifewine** [comment]
with a proper since on 3.4, do we need the check at all?

**Comment by mambocab** [comment]
Hah, no, we don't need the check. Awesome, +1.

**Comment by knifewine** [comment]
just to be sure, I ran the tests locally on 3.4 and they pass. merging now.

**Pull request merged**
