### PR TITLE
Update tests after changing behaviour of LWTLs on non-existing partit…

### PR DESCRIPTION
**Pull request by ifesdjeen**
…ions vs empty statics

for [CASSANDRA-12060](https://issues.apache.org/jira/browse/CASSANDRA-12060)

### CODE REVIEW

**Comment by ptnapoleon** [comment]
I see the ticket has patches for 2.1+. Then we can rely on every major C* version to have the same behavior in these tests?

**Comment by ifesdjeen** [comment]
Yes, that was the only reason to make a change to 2.1: to keep things consistent across the versions (even though the behaviour was consistent, just different prior to that change). 

I'll wait for review and merge that when C* ticket is reviewed.

**Comment by ptnapoleon** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-12724

**Comment by ifesdjeen** [comment]
Looks like this particular commit is already merged in.

**Pull request closed without merging**
