### PR TITLE
CASSANDRA-9902 Fix configurations dtest on windows

### PR DESCRIPTION
**Pull request by pauloricardomg**
* Fix is platform independent, should work on Linux but I didn't have the chance to test.
* Also fixed configuration_test.change_durable_writes_test
More information: https://issues.apache.org/jira/browse/CASSANDRA-9902

### CODE REVIEW

**Comment by ptnapoleon** [comment]
I'll test on linux on monday . Can you check out the style warning travis is complaining about though?

**Comment by pauloricardomg** [comment]
travis checks now passing

**Comment by ptnapoleon** [comment]
This does still work on linux, at least for me.

**Comment by ptnapoleon** [comment]
I'm +1 overall. Waiting on Josh's approval before merging.

**Comment by ptnapoleon** [comment]
Nevermind, Josh is away. Merging.

**Pull request merged**
