### PR TITLE
Remove all uses of known failure annotation

### PR DESCRIPTION
**Pull request by ptnapoleon**
@mambocab, @smccarthy788, @mshuler

### CODE REVIEW

**Comment by mshuler** [comment]
Are bin/collect_known_failures.py and the `def known_failure()` in tools/decorators.py still needed?

**Comment by ptnapoleon** [comment]
There are still systems that run that script in bin/. The annotation is _probably_ not needed, but no need to remove it just yet.

**Comment by mshuler** [comment]
Thanks. Is there a run with `DTEST_BRANCH` set to this one? If not, I could go cobble one together to validate.

**Comment by ptnapoleon** [comment]
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-dtest/23/console

**Comment by mshuler** [comment]
lgtm, if tests out fine. +1

**Comment by ptnapoleon** [comment]
CI looks fine, failures are unrelated:
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-dtest/23/testReport/

**Pull request merged**
